### ISSUE TITLE
Autoware ROSBAG demo, no /points_map

### ISSUE THREAD

**Issue by bfroemel** [Autoware-AI/documentation#5]
### Required information:

- Operating system and version:
  -  Ubuntu 18.04
- Autoware installation type:
  - Docker, autoware/autoware:latest-melodic-cuda
- Autoware version or commit hash
  - 1.14.0
- ROS distribution and version:
  - Melodic
- ROS installation type:
  - Docker
- Package or library, if applicable:
  - map_file

### Description of the bug
In the autoware rosbag demo `/points_map` is not produced, consequently most of the demo does not appear to work. 

Here another user who encountered this issue: https://answers.ros.org/question/348637/autoware-rosbag-demo-no-points_map/

### Steps to reproduce the bug

Follow the demo instructions from here: https://github.com/Autoware-AI/documentation/tree/master/autoware_quickstart_examples
The final step: "Un-pausing the simulation after starting the Map will show the pointcloud map in Rviz." does not work, i.e., rviz does not show the pointcloud (also in the the Quick Start tab of the ARM, there is no "OK" displayed next to the Map launcher file location).

### Expected behavior
The node map_file/points_map_loader should correctly load the pcd files from `~/.autoware/data/map/pointcloud_map/`, publish appropriately to `/points_map`, and Rviz should in consequence be able to show the pointcloud map (and other depending autoware features like localization, detection, .. should become functional in the demo).

**Comment by thiagodeborba** [comment]
I just installed Autoware.ai v1.14.
I am trying to run the Demo but I can not see the point cloud map.
How can I solve this problem?

**Comment by JWhitleyWork** [comment]
@thiagodeborba Please direct support requests to [ROS Answers](https://answers.ros.org/) with the `autoware` tag.
